### PR TITLE
make it noarch

### LINKED ISSUE #47: Make noarch: python?
Is there a compelling reason to keep this with many builds? I'll take a look at upstreams, but _think_ it's used by `conda-feedstock` (if that's even a hard limit anymore)...

### PR DESCRIPTION
**Pull request by matthiasdiener**
Fixes #47.

`noarch: python` was removed in #10 (py2k selector).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Ready for review @conda-forge/arrow

**Review by bollwyvl — APPROVED** [review]
LGTM! thoughts @ocefpaf ?

**Comment by ocefpaf** [comment]
> LGTM! thoughts @ocefpaf ?

I don't remember if we had any reasons to not make it noarch. I'd say let's go for it and, if we find any issues, we can pull the packages and revert.

**Comment by matthiasdiener** [comment]
> > LGTM! thoughts @ocefpaf ?
> 
> I don't remember if we had any reasons to not make it noarch. I'd say let's go for it and, if we find any issues, we can pull the packages and revert.

From what I could see, noarch was removed due to a py2k selector (#10), which is long gone.

**Comment by ocefpaf** [comment]
> From what I could see, noarch was removed due to a py2k selector (#10), which is long gone.

Yeah. The odd thing was that we should've used noarch with >=3 or re-added  it once we removed the selector. Probably an oversight rather than a real reason. But we will figure it out soon :smile:

**Pull request merged**
